[#6422] pagination issues fixes
liqd/a4-meinberlin pull request #4513
Opened 2022-09-26 11:36 UTC by khamui

2022-09-26 15:35 UTC, goapunk commented on meinberlin/apps/budgeting/assets/PaginationButton.jsx
> +      return `${props.pageIndex} / ${props.pageCount}`
the text color is grey for this and not very readable, I assume we should also use the default black here?

2022-09-26 15:35 UTC, goapunk requested changes
nice fixes! just one small thing

2022-09-26 15:37 UTC, goapunk commented on meinberlin/apps/budgeting/assets/Pagination.jsx
> +              isDisabled
we should pass `false` here I think, otherwise the text is grey and hard to read

2022-09-27 09:53 UTC, khamui commented
just realize #4510 is just fixed for the react pagination, still the django pagination needs to be done, but not sure if this is quite a bit of rework (at least for me).

would it be fine to do that in another PR so this can be merged already?

2022-09-27 11:03 UTC, goapunk approved these changes
nice, looks good to me!

2022-09-27 12:16 UTC, phillimorland requested changes
few questions?

2022-09-28 14:12 UTC, phillimorland requested changes
cool, just a few comments and I just noticed when checking it this time that we don't use BEM, maybe we can change pagination-item to pagination__item?

2022-09-28 14:12 UTC, phillimorland commented on meinberlin/assets/scss/_variables.scss
> +$breakpoint-xxs: 23.75rem !default;
why do you want to add an additional breakpoint? also this is added as a min width value but you use it in a max width query, we don't really want to add additional break points as it add complexity, applying the same style up to a width of 512px is pretty standard, bootstraps first breakpoint is 576 so we aren't far off the norm.

2022-09-28 14:28 UTC, phillimorland commented on meinberlin/assets/scss/components/_pagination.scss
> +}
maybe 0.7 or 0.75 just from having a quick play in the browser but your call

2022-09-29 11:24 UTC, fuzzylogic2000 commented
What is the status here? @khamui It is finished and can be reviewed again? Will you do that @phillimorland ? Or should I? (I am not sure I will notice everything you talked about.)

2022-09-29 11:25 UTC, phillimorland commented
@fuzzylogic2000 sorry didn't see the re-tag, will take a look now

2022-09-29 11:35 UTC, phillimorland approved these changes
perfect! :)

2022-09-29 11:35 UTC, merged