[4920]account/email: adding template for account already exists case …
liqd/a4-meinberlin pull request #4956
Opened 2023-02-13 13:28 UTC by khamui

…and add test command

closes #4920

2023-02-14 08:08 UTC, fuzzylogic2000 requested changes
Did it work for you? I get
```
Internal Server Error: /accounts/signup/
Traceback (most recent call last):
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/allauth/decorators.py", line 20, in wrap
    resp = function(request, *args, **kwargs)
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/allauth/account/views.py", line 234, in dispatch
    return super(SignupView, self).dispatch(request, *args, **kwargs)
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/allauth/account/views.py", line 77, in dispatch
    response = super(RedirectAuthenticatedUserMixin, self).dispatch(
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/allauth/account/views.py", line 207, in dispatch
    return super(CloseableSignupMixin, self).dispatch(request, *args, **kwargs)
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/allauth/account/views.py", line 105, in post
    response = self.form_valid(form)
  File "/home/katharina/a4-meinberlin/venv/lib/python3.10/site-packages/allauth/account/views.py", line 248, in form_valid
    self.user = form.save(self.request)
  File "/home/katharina/a4-meinberlin/meinberlin/apps/users/forms.py", line 115, in save
    user.get_newsletters = self.cleaned_data["get_newsletters"]
AttributeError: 'NoneType' object has no attribute 'get_newsletters'
```
I hoped it would be as easy as adding the missing email, but seems it's not. :(

2023-02-14 10:37 UTC, khamui commented
@fuzzylogic2000 @Rineee now it validates the field, but does not send the email. Do you have an idea what I miss here?

2023-02-14 10:56 UTC, fuzzylogic2000 commented
> @fuzzylogic2000 @Rineee now it validates the field, but does not send the email. Do you have an idea what I miss here?

@khamui Did you check the allauth code? Wher is that done and validated? I guess, it shold also sent that email in that error and not only raise the validationError? But I don't know and would also need to check the allauth code.

2023-02-14 17:11 UTC, khamui commented
> > @fuzzylogic2000 @Rineee now it validates the field, but does not send the email. Do you have an idea what I miss here?
> 
> @khamui Did you check the allauth code? Wher is that done and validated? I guess, it shold also sent that email in that error and not only raise the validationError? But I don't know and would also need to check the allauth code.

@fuzzylogic2000 it seems that I cannot throw a Validation error in `save()` and in `clean_email` I do not have `request`. The last commit shows the validation error and sends the email. But the email does not contain a proper reset_password link, because there is no request...maybe we can talk about it, maybe you have an idea or a hint :)

2023-02-15 14:58 UTC, khamui commented on meinberlin/apps/users/forms.py
> +        if user:
the super().save() sends the email and returns None in case of email already exists.

2023-02-17 09:49 UTC, fuzzylogic2000 approved these changes
Perfect!

2023-02-17 09:49 UTC, merged