WIP [issues] styling issues for release
liqd/a4-meinberlin pull request #5172
Opened 2023-07-04 15:44 UTC by philli-m

2023-07-05 14:10 UTC, philli-m commented
@goapunk I did not manage to disable the local csp to test capcha, if you have any suggestions happy to accept

2023-07-17 07:42 UTC, goapunk commented
@philli-m the rating styling looks off

2023-07-17 10:25 UTC, philli-m commented on meinberlin/assets/scss/components/_list_item.scss
> -}
@goapunk this commit for some reason reset the other changes from the first commit, no clue why?!

2023-07-17 14:14 UTC, goapunk requested changes
Looks good, only a small typo. I couldn't reproduce https://github.com/liqd/a4-meinberlin/issues/5171 either so will have to see.

2023-07-17 15:01 UTC, philli-m commented on meinberlin/assets/scss/components/_list_item.scss
> +        flex-direction: space-between;
yes...

2023-07-17 15:22 UTC, goapunk approved these changes
cool, thanks for all fixes!

2023-07-17 15:24 UTC, merged