[WIP] [#8652] Kiez Profile List View
liqd/a4-meinberlin pull request #5894
Opened 2024-12-17 14:53 UTC by sevfurneaux

**Describe your changes**
This PR adds the Kiez profile list view.

**Tasks**
- [X] PR name contains story or task reference
- [ ] Steps to recreate and test the changes
- [ ] Documentation (docs and inline)
- [ ] Tests (including n+1 and django_assert_num_queries where applicable)
- [ ] Changelog

2025-01-07 06:56 UTC, vellip requested changes
Thank you for your implementation! I left a few change requests, but looks good overall.

2025-01-07 06:56 UTC, vellip commented on meinberlin/react/kiezradar/SearchProfiles.jsx
> +        <h3 className="search-profile__title">{profile.name}</h3>
It should also show what filters have been set, no?
![CleanShot 2025-01-07 at 07 29 19@2x](https://github.com/user-attachments/assets/61ca59d5-3be4-4588-8cda-db2e1fc2446f)

2025-01-07 06:56 UTC, vellip commented on meinberlin/assets/scss/components_user_facing/_search-profiles.scss
> +.search-profile__button:focus {
I would skip the focus style as that normally already has the focus-highlight ring. We don't underline links on focus anywhere else on the page, normally.

2025-01-07 06:56 UTC, vellip commented on meinberlin/assets/scss/components_user_facing/_search-profiles.scss
> +    position: fixed;
I would suggest we keep the normal `alert`layout, as it's more consistent to the user that way. afaik regular alerts are not fixed but in document flow

2025-01-07 06:56 UTC, vellip commented on meinberlin/react/kiezradar/SearchProfiles.jsx
> +            </h2>
You can keep both the `h2`s in each of the cases (length === 0 // length !== 0) below the alert and just change the text inside the h2 based on the case and then skip the React.Fragments (<>)

2025-01-07 06:56 UTC, vellip commented on meinberlin/react/kiezradar/SearchProfiles.jsx
> +      })
you can use `updateItem` for this i gather. https://github.com/liqd/a4-meinberlin/blob/a73f7752a0dc127ca0d1451d7b488fb9150c347b/meinberlin/react/contrib/helpers.js#L3

2025-01-07 06:56 UTC, vellip commented on meinberlin/react/kiezradar/SearchProfiles.jsx
> +function Buttons ({ onEdit, onDelete, loading }) {
Could you give this some more descriptive name after you split the components into separate files? Otherwise this would probably show up for a lot of autocompletes in IDE

2025-01-07 06:56 UTC, vellip commented on meinberlin/react/kiezradar/SearchProfiles.jsx
> +function Alert ({ onClose }) {
Can you re-use node-modules/adhocracy4/static/Alert.jsx? (path might not be 100% exact)

2025-01-07 10:30 UTC, sevfurneaux commented
> Thank you for your implementation! I left a few change requests, but looks good overall.

Happy New Year! Thanks for the feedback, will take a look now 👀

2025-01-07 15:56 UTC, sevfurneaux commented on meinberlin/react/kiezradar/SearchProfiles.jsx
> +}
All components now split 👍

2025-01-07 15:58 UTC, sevfurneaux commented on meinberlin/react/kiezradar/SearchProfiles.jsx
> +      })
Added `updateItem` 👍

2025-01-07 16:05 UTC, sevfurneaux commented on meinberlin/react/kiezradar/SearchProfiles.jsx
> +function Alert ({ onClose }) {
I attempted to add this:

`import Alert from 'adhocracy4/adhocracy4/static/Alert'`

and

```
<Alert
  type="success"
  message={alertHeadlineText}
  onClick={() => setAlert(false)}
/>
```

But this component looks outdated. It doesn't use the the latest alert classes such as `alert__content`, `alert__headline` and `alert__text`.

It is also not possible to pass in both a `headline` and `text` prop, and only a singular `message`.

I've kept my `SearchProfileAlert` for now, but maybe we could resolve the above in a PR and add a ticket to make `Alert` up-to-date?

2025-01-08 08:04 UTC, vellip approved these changes
LGTM thanks!

2025-01-08 08:05 UTC, merged